# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: route.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "Route" do
    repeated :duration, :uint32, 1
    repeated :latitude, :double, 2
    repeated :longitude, :double, 3
    repeated :altitude, :int32, 4
    repeated :satellites, :uint32, 5
    optional :b6, :string, 6
    optional :b7, :string, 7
    optional :b8, :string, 8
    optional :timestamp, :message, 9, "Route.DateTime"
  end
  add_message "Route.Date" do
    optional :year, :uint32, 1
    optional :month, :uint32, 2
    optional :day, :uint32, 3
  end
  add_message "Route.Time" do
    optional :hour, :uint32, 1
    optional :minute, :uint32, 2
    optional :seconds, :uint32, 3
    optional :milliseconds, :uint32, 4
  end
  add_message "Route.DateTime" do
    optional :date, :message, 1, "Route.Date"
    optional :time, :message, 2, "Route.Time"
  end
end

Route = Google::Protobuf::DescriptorPool.generated_pool.lookup("Route").msgclass
Route::Date = Google::Protobuf::DescriptorPool.generated_pool.lookup("Route.Date").msgclass
Route::Time = Google::Protobuf::DescriptorPool.generated_pool.lookup("Route.Time").msgclass
Route::DateTime = Google::Protobuf::DescriptorPool.generated_pool.lookup("Route.DateTime").msgclass
